// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BookstoreAPP.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace BookstoreAPP.Models
{
    public partial class BookstoreDbContext
    {
        private IBookstoreDbContextProcedures _procedures;

        public virtual IBookstoreDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new BookstoreDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IBookstoreDbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class BookstoreDbContextProcedures : IBookstoreDbContextProcedures
    {
        private readonly BookstoreDbContext _context;

        public BookstoreDbContextProcedures(BookstoreDbContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GenerateDailySalesReportResult>> GenerateDailySalesReportAsync(DateOnly? ReportDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ReportDate",
                    Value = ReportDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GenerateDailySalesReportResult>("EXEC @returnValue = [dbo].[GenerateDailySalesReport] @ReportDate = @ReportDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
