// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BookstoreAPP.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace BookstoreAPP.Models
{
    public partial interface IBookstoreDbContextProcedures
    {
        Task<List<GenerateDailySalesReportResult>> GenerateDailySalesReportAsync(DateOnly? ReportDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
